name: build

on:
  pull_request:
    branches:
    - 'main'
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Create gitignored loginData file
      run: |
        cd main
        touch loginData.hpp
        echo '#include <string_view>' >> loginData.hpp
        echo 'constexpr std::string_view StaSsid = "ssid";' >> loginData.hpp
        echo 'constexpr std::string_view StaPassword = "password";' >> loginData.hpp
        echo 'constexpr std::string_view ApSsid = "apssid";' >> loginData.hpp
        echo 'constexpr std::string_view ApPassword = "appassword";' >> loginData.hpp
        cat loginData.hpp
      shell: bash

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v4.4
        target: esp32
